### ISSUE TITLE
Upgrade SQLx dependency to 0.6.x

### ISSUE THREAD

**Issue by billy1624** [SeaQL/sea-query#356]
## Motivation

Upgrading SQLx dependency as well as the downstream dependencies such as `time`, `uuid`, `bigdecimal`, etc.

## Tasks

- [x] Upgrade to SQLx 0.6.x
- [x] Upgrade to time 0.3.x
    - https://github.com/SeaQL/sea-query/issues/340
- [x] Upgrade to uuid 1.x
    - https://github.com/SeaQL/sea-query/issues/325
- [x] Update the drivers ([sqlx](https://crates.io/crates/sqlx), [postgres](https://crates.io/crates/postgres) and [rustqlite](https://crates.io/crates/rusqlite)) to bind all upgraded value types
- [x] Upgrade to bigdecimal 0.3.x

## Additional Information

Potential Breaking Changes
* https://github.com/launchbadge/sqlx/issues/1618  
  SQLite `chrono::DateTime<FixedOffset>` timezone fix
    * `DateTime<FixedOffset>` will be stored in SQLite with the correct timezone instead of always in UTC.
      This was flagged as a "potentially breaking change" since it changes how dates are sent to SQLite.
* https://github.com/launchbadge/sqlx/issues/1901
  Pool fixes and breaking changes
    * Renamed `PoolOptions::connect_timeout` to `acquire_timeout` for clarity.

**Comment by ikrivosheev** [comment]
@billy1624 please, add `bigdecimal` to Tasks.

**Comment by billy1624** [comment]
Hey @ikrivosheev, feel free to edit my comment :)

**Comment by ikrivosheev** [comment]
@billy1624 @tyt2y3 I think we need to agree! Support both `time`, `uuid`, `bigdecimal` versions or support only latest?

**Comment by tyt2y3** [comment]
I think we should only support latest

**Comment by ikrivosheev** [comment]
@tyt2y3 sounds good

**Comment by tyt2y3** [comment]
Okay. So after some thought, I think our dependency policy would be follows: we only support the latest release of a upstream dependency. And in SeaORM we simply follow whatever version sqlx uses.

**Comment by tyt2y3** [comment]
I realize that it's a much less maintenance burden to backport features to an older branch than to trying to make it all work together in one codebase.

**Comment by tyt2y3** [comment]
So at any time we only maintain two sea-query branches, the latest `master` and whatever version sea-orm is pinned to.

**Comment by ikrivosheev** [comment]
@tyt2y3 I add PR

**Comment by ikrivosheev** [comment]
@tyt2y3 I think we can close this issue, because  sqlx is upgraded.

**Comment by tyt2y3** [comment]
SO cool, I am waiting the moment the CI passes

**Comment by ikrivosheev** [comment]
Cool! CI pass: https://github.com/SeaQL/sea-query/actions/runs/2596551981
